tabl_it<-function(dig=1){
  charge<<-charge_int
return(paste(
  "<h1>Italie</h1>",
  "<table style=\"width:100%\" border=1>",
ligne_date(),
f_row("Produit interieur brut","it.td.b1g_s1_7ch",VT,VA,b_int,b_int_old,dig=dig,bold=T,n_prev=2),
f_row("Consommation privee","it.td.p3_s145_7ch",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
f_row("Investissement","it.td.p51g_7ch",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
f_row("Consommation publique","it.td.p3_s13_7ch",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
f_row("Exportations","it.td.p6_7ch",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
f_row("Importations","it.td.p7_7ch",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
"<tr><td><b>Contributions</b></td></tr>",
f_row("Demande interieure hors stocks","it.di.contrib",NIV,NIV_AN,b_int,b_int_old,"it.di.contrib.an",dig=dig,n_prev=2),
f_row("Variation de stocks","it.stocks.contrib",NIV,NIV_AN,b_int,b_int_old,"it.stocks.contrib.an",dig=dig,n_prev=2),
f_row("Commerce exterieur","it.comext.contrib",NIV,NIV_AN,b_int,b_int_old,"it.comext.contrib.an",dig=dig,n_prev=2),
"<tr><td><b>Detail investissement</b></td></tr>",
f_row("Investissement en construction","it.td.p51g_n11kg_7ch",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
f_row("Investissement en equipement","it.td.p51g_n11mg_7ch",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
f_row("Investissement autre","it.td.p51g_n1157g_7ch",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
"</table>",
"<h1>Compte des menages</h1>",
"<table style=\"width:100%\" border=1>",
ligne_date(),
f_row("RDB Insee","it.td.rdb_insee_3",VT,VA,b_int,b_int_old,bold=T,dig=dig,n_prev=3),
f_row("Emploi salarie","it.td.emploi_sal_3",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
f_row("Salaires","it.td.smpt_3",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
f_row("Salaires reels","it.td.smpt_7ch",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
f_row("Taux d'activite","it.td.tx_act",NIV,NIV_A,b_int,b_int_old,dig=dig,n_prev=3),
f_row("Population active","it.td.pop_act_3",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
f_row("Emploi total","it.td.emploi_3",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
f_row("Taux de chomage","it.td.tx_chomage",NIV,NIV_A,b_int,b_int_old,bold=T,dig=dig,n_prev=3),
f_row("Inflation energetique","it.td.ipch_nrj_bis",GA,GA_A,b_int,b_int_old,dig=dig,n_prev=2),
f_row("Inflation alimentaire","it.td.ipch_alim_hors_drogue",GA,GA_A,b_int,b_int_old,dig=dig,n_prev=2),
f_row("Inflation sous-jacente","it.td.ipch_sj",GA,GA_A,b_int,b_int_old,dig=dig,n_prev=2),
f_row("Inflation totale","it.td.ipch_tot",GA,GA_A,b_int,b_int_old,bold=T,dig=dig,n_prev=2),
f_row("Deflateur de la consommation","it.td.p3_s145_9",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
f_row("Taux d'epargne","it.td.tx_epargne",NIV,NIV_A,b_int,b_int_old,bold=T,dig=dig,n_prev=3),
f_row("Pouvoir d'achat","it.td.rdb_insee_7",VT,VA,b_int,b_int_old,bold=T,dig=dig,n_prev=3),
"</table>",sep=""))}


