tabl_es<-function(dig=1){
  charge<<-charge_int
  return(paste(
    "<h1>Espagne</h1>",
    "<table style=\"width:100%\" border=1>",
ligne_date(),
f_row("Produit interieur brut","es.td.b1g_7ch_ind",VT,VA,b_int,b_int_old,dig=dig,bold=T,n_prev=2),
f_row("Consommation privee","es.td.p3_s145_7ch_ind",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
f_row("Investissement","es.td.p51g_7ch_ind",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
f_row("Consommation publique","es.td.p3_s13_7ch_ind",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
f_row("Exportations","es.td.p6_7ch_ind",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
f_row("Importations","es.td.p7_7ch_ind",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
"<tr><td><b>Contributions</b></td></tr>",
f_row("Demande interieure hors stocks","es.di.contrib",NIV,NIV_AN,b_int,b_int_old,"es.di.contrib.an",dig=dig,n_prev=2),
f_row("Variation de stocks","es.stocks.contrib",NIV,NIV_AN,b_int,b_int_old,"es.stocks.contrib.an",dig=dig,n_prev=2),
f_row("Commerce exterieur","es.comext.contrib",NIV,NIV_AN,b_int,b_int_old,"es.comext.contrib.an",dig=dig,n_prev=2),
"<tr><td><b>Detail investissement</b></td></tr>",
f_row("Investissement en construction","es.td.p51g_n11kg_7ch_ind",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
f_row("Investissement en equipement","es.td.p51g_n11mg_7ch_ind",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
"</table>",
"<h1>Compte des menages</h1>",
"<table style=\"width:100%\" border=1>",
ligne_date(),
f_row("RDB","es.td.b6g_s145_3",VT,VA,b_int,b_int_old,bold=T,dig=dig,n_prev=3),
f_row("Emploi salarie","es.td.emploi_sal_3",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
f_row("Salaires","es.smpt",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
f_row("Salaires reels","es.smpt_7ch",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
f_row("Taux d'activite","es.tx_act",NIV,NIV_A,b_int,b_int_old,dig=dig,n_prev=3),
f_row("Population active","es.td.pop_act_3",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
f_row("Emploi total","es.td.emploi_3",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
f_row("Taux de chomage","es.td.tx_chomage_pe",NIV,NIV_A,b_int,b_int_old,bold=T,dig=dig,n_prev=2),
f_row("Inflation energetique","es.td.ipch_nrj",GA,GA_A,b_int,b_int_old,dig=dig,n_prev=2),
f_row("Inflation alimentaire","es.td.ipch_alim",GA,GA_A,b_int,b_int_old,dig=dig,n_prev=2),
f_row("Inflation sous-jacente","es.td.ipch_sj",GA,GA_A,b_int,b_int_old,dig=dig,n_prev=2),
f_row("Inflation totale","es.td.ipch_tot",GA,GA_A,b_int,b_int_old,bold=T,dig=dig,n_prev=2),
f_row("Deflateur de la consommation","es.td.p3_s145_9",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
f_row("Taux d'epargne","es.tx_ep",NIV,NIV_A,b_int,b_int_old,bold=T,dig=dig,n_prev=3),
f_row("Pouvoir d'achat","es.td.b6g_s145_7",VT,VA,b_int,b_int_old,bold=T,dig=dig,n_prev=3),
"</table>",sep=""))}



