tabl_ze<-function(dig=1){
  charge<<-charge_int
return(paste(
  "<h1>Zone euro</h1>",
  "<table style=\"width:100%\" border=1>",
  ligne_date(),
  f_row("Produit intérieur brut","ze.pib",VT,VA,b_int,b_int_old,dig=dig,bold=T,n_prev=2),
  f_row("Consommation privée","ze.conso",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
  f_row("Investissement","ze.fbcf",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
  f_row("Consommation publique","ze.conso_pub",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
  f_row("Exportations","ze.export",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
  f_row("Importations","ze.import",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
  "<tr><td><b>Contributions</b></td></tr>",
  f_row("Demande intérieure hors stocks","ze.di.contrib",NIV,NIV_AN,b_int,b_int_old,"ze.di.contrib.an",b_int,b_int_old,dig=dig,n_prev=2),
  f_row("Variation de stocks","ze.stocks.contrib",NIV,NIV_AN,b_int,b_int_old,"ze.stocks.contrib.an",b_int,b_int_old,dig=dig,n_prev=2),
  f_row("Commerce extérieur","ze.comext.contrib",NIV,NIV_AN,b_int,b_int_old,"ze.comext.contrib.an",b_int,b_int_old,dig=dig,n_prev=2),
  "<tr><td><b>Detail investissement</b></td></tr>",
  f_row("Investissement en construction","ze.fbcf_cons",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
  f_row("Investissement en équipement","ze.fbcf_eq",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
  "</table>",
  "<h1>Compte des ménages</h1>",
  "<table style=\"width:100%\" border=1>",
  ligne_date(),
  f_row("RDB","ze.b6g_paid",VT,VA,b_int,b_int_old,bold=T,dig=dig,n_prev=3),
  f_row("Emploi salarié","ze.emploi_sal",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
  f_row("Salaires","ze.smpt",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
  f_row("Salaires réels","ze.smptr",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
  f_row("Taux d'activité","ze.tx_activite_sa",NIV,NIV_A,b_int,b_int_old,dig=dig,n_prev=3),
  f_row("Population active","ze.pop_active_sa",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
  f_row("Emploi total","ze.emploi_tot_sa",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
  f_row("Taux de chômage","ze.tx_chom",NIV,NIV_A,b_int,b_int_old,bold=T,dig=dig,n_prev=3),
  f_row("Inflation énergetique","ze.ipch_trim_nrj_sa",GA,GA_A,b_int,b_int_old,dig=dig,n_prev=2),
  f_row("Inflation alimentaire","ze.ipch_trim_alim_sa",GA,GA_A,b_int,b_int_old,dig=dig,n_prev=2),
  f_row("Inflation sous-jacente","ze.ipch_trim_core_sa",GA,GA_A,b_int,b_int_old,dig=dig,n_prev=2),
  f_row("Inflation totale","ze.ipch_trim_tot_sa",GA,GA_A,b_int,b_int_old,bold=T,dig=dig,n_prev=2),
  f_row("Déflateur de la consommation","ze.def_conso",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
  f_row("Taux d'epargne","ze.tx_ep",NIV,NIV_A,b_int,b_int_old,bold=T,dig=dig,n_prev=3),
  f_row("Pouvoir d'achat","ze.rdbr_sa",VT,VA,b_int,b_int_old,bold=T,dig=dig,n_prev=3),
  "</table>",sep=""))}