tabl_jp<-function(dig=1){
  charge<<-charge_int
  return(paste(
    "<h1>Japon</h1>",
    "<table style=\"width:100%\" border=1>",
  ligne_date(),
  f_row("Produit interieur brut","jp.pib",VT,VA,b_int,b_int_old,dig=dig,bold=T,n_prev=4),
  f_row("Consommation privee","jp.conso",VT,VA,b_int,b_int_old,dig=dig,n_prev=4),
  f_row("Investissement","jp.inv",VT,VA,b_int,b_int_old,dig=dig,n_prev=4),
  f_row("Consommation publique","jp.conso_pu",VT,VA,b_int,b_int_old,dig=dig,n_prev=4),
  f_row("Exportations","jp.exp_trim",VT,VA,b_int,b_int_old,dig=dig,n_prev=4),
  f_row("Importations","jp.imp",VT,VA,b_int,b_int_old,dig=dig,n_prev=4),
  "<tr><td><b>Contributions</b></td></tr>",
  f_row("Demande interieure hors stocks","jp.di.contrib",NIV,NIV_AN,b_int,b_int_old,"jp.di.contrib.an",dig=dig,n_prev=4),
  f_row("Variation de stocks","jp.stocks.contrib",NIV,NIV_AN,b_int,b_int_old,"jp.stocks.contrib.an",dig=dig,n_prev=4),
  f_row("Commerce exterieur","jp.comext.contrib",NIV,NIV_AN,b_int,b_int_old,"jp.comext.contrib.an",dig=dig,n_prev=4),
  "<tr><td><b>Detail investissement</b></td></tr>",
  f_row("Investissement public","jp.inv_pu",VT,VA,b_int,b_int_old,dig=dig,n_prev=4),
  f_row("Investissement prive des menages","jp.inv_priv_l",VT,VA,b_int,b_int_old,dig=dig,n_prev=4),
  f_row("Investissement des entreprises","jp.inv_priv_hl",VT,VA,b_int,b_int_old,dig=dig,n_prev=4),
  "</table>",
  "<h1>Compte des menages</h1>",
  "<table style=\"width:100%\" border=1>",
  ligne_date(),
  f_row("RDB","jp.rdb_v_sa",VT,VA,b_int,b_int_old,bold=T,dig=dig,n_prev=8),
  f_row("Emploi salarie","jp.emp_salarie_q",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
  f_row("Salaires nominaux","jp.smpt_q",VT,VA,b_int,b_int_old,dig=dig,n_prev=4),
  f_row("Population active","jp.popactive_q",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
  f_row("Emploi total","jp.emp",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
  f_row("Taux de chomage","jp.u",NIV,NIV_A,b_int,b_int_old,bold=T,dig=dig,n_prev=3),
  f_row("Inflation energetique","jp.ipc_energ",GA,GA_A,b_int,b_int_old,dig=dig,n_prev=3),
  f_row("Inflation alimentaire","jp.ipc_alim",GA,GA_A,b_int,b_int_old,dig=dig,n_prev=3),
  f_row("Inflation sous-jacente","jp.ipc_sj",GA,GA_A,b_int,b_int_old,dig=dig,n_prev=3),
  f_row("Inflation totale","jp.ipc",GA,GA_A,b_int,b_int_old,bold=T,dig=dig,n_prev=3),
  f_row("Deflateur de la consommation","jp.defconso",VT,VA,b_int,b_int_old,dig=dig,n_prev=4),
  f_row("Taux d'epargne","jp.tx_ep",NIV,NIV_A,b_int,b_int_old,bold=T,dig=dig,n_prev=8),
  f_row("Pouvoir d'achat","jp.rdb_r",VT,VA,b_int,bold=T,dig=dig,n_prev=8),
  "</table>",sep=""))}
  

