tabl_us<-function(dig=1){
  charge<<-charge_int
return(paste(
  "<h1>Etats-Unis</h1>",
  "<table style=\"width:100%\" border=1>",
  ligne_date(),
  f_row("Produit interieur brut","us.pib",VT,VA,b_int,b_int_old,dig=dig,bold=T,n_prev=2),
  f_row("Consommation privee","us.conso",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
  f_row("Investissement prive","us.inv_hs",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
  f_row("Depenses gouvernementales","us.dp",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
  f_row("Exportations","us.exports",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
  f_row("Importations","us.imports",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
  "<tr><td><b>Contributions</b></td></tr>",
  f_row("Demande interieure hors stocks","us.di_contrib",NIV,NIV_AN,b_int,b_int_old,"us.di.contrib.an",dig=dig,n_prev=2),
  f_row("Variation de stocks","us.stocks.contrib",NIV,NIV_AN,b_int,b_int_old,"us.stocks.contrib.an",dig=dig,n_prev=2),
  f_row("Commerce exterieur","us.comext.contrib",NIV,NIV_AN,b_int,b_int_old,"us.comext.contrib.an",dig=dig,n_prev=2),
  "</table>",
  "<h1>Compte des menages</h1>",
  "<table style=\"width:100%\" border=1>",
  ligne_date(),
  f_row("RDB","us.cm_rdb",VT,VA,b_int,b_int_old,bold=T,dig=dig,n_prev=2),
  f_row("Emploi salarie","us.emp_sal",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
  f_row("Salaires nominaux","us.smpt",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
  f_row("Population active","us.pop_act",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
  f_row("Emploi total","us.emp",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
  f_row("Taux de chomage","us.u",NIV,NIV_A,b_int,b_int_old,bold=T,dig=dig,n_prev=2),
  f_row("Inflation energetique","us.ipc_nrj",GA,GA_A,b_int,b_int_old,dig=dig,n_prev=2),
  f_row("Inflation alimentaire","us.ipc_fd",GA,GA_A,b_int,b_int_old,dig=dig,n_prev=2),
  f_row("Inflation sous-jacente","us.ipc_sj",GA,GA_A,b_int,b_int_old,dig=dig,n_prev=2),
  f_row("Inflation totale","us.ipc",GA,GA_A,b_int,b_int_old,bold=T,dig=dig,n_prev=2),
  f_row("Deflateur de la consommation","us.defconso",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
  f_row("Taux d'epargne","us.txep",NIV,NIV_A,b_int,b_int_old,bold=T,dig=dig,n_prev=2),
  f_row("Pouvoir d'achat","us.cm_rdbr",VT,VA,b_int,b_int_old,bold=T,dig=dig,n_prev=2),
  "</table>",sep=""))}
  
