tabl_syn<-function(dig=1){
  charge<<-charge_int
  return(paste(
    "<h1>Synthese</h1>",
    "<table style=\"width:100%\" border=1>",
    ligne_date(),
    f_row("PIB des economies avancees","syn.pib_ea",VT,VA,b_int,b_int_old,dig=dig,bold=T,n_prev=2),
    "</table>",
    
    "<h1>Zone euro</h1>",
    "<table style=\"width:100%\" border=1>",
    ligne_date(),
    f_row("Produit intérieur brut","syn.ze.pib",VT,VA,b_int,b_int_old,dig=dig,bold=T,n_prev=2),
    f_row("Consommation privée","syn.ze.conso",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
    f_row("Investissement","syn.ze.fbcf",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
    f_row("Consommation publique","syn.ze.conso_pub",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
    f_row("Exportations","syn.ze.export",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
    f_row("Importations","syn.ze.import",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
    "<tr><td><b>Contributions</b></td></tr>",
    f_row("Demande intérieure hors stocks","syn.ze.di.contrib",NIV,NIV_AN,b_int,b_int_old,"syn.ze.di.contrib.an",b_int,b_int_old,dig=dig,n_prev=3),
    f_row("Variation de stocks","syn.ze.stocks.contrib",NIV,NIV_AN,b_int,b_int_old,"syn.ze.stocks.contrib.an",b_int,b_int_old,dig=dig,n_prev=3),
    f_row("Commerce extérieur","syn.ze.comext.contrib",NIV,NIV_AN,b_int,b_int_old,"syn.ze.comext.contrib.an",b_int,b_int_old,dig=dig,n_prev=3),
    "Au deuxième trimestre 2019, la FBCF de l'Irlande a crû de plus de 182 % contribuant ainsi 
    positivement à l'investissement en zone euro à hauteur de 5,4 points. 
    Contrepartie de cette hausse de l'investissement, l'augmentation des importations irlandaises 
    (+43 % au deuxième trimestre) a contribué pour 2,6 points à celle des importations de la zone.
    Comme cela a pu déjà survenir par le passé, par exemple en 2017, de telles variations ont conduit 
    à exclure l'Irlande des comptes présentés ci-dessous.",
    "</table>",
    
    "<h1>France (20%*)</h1>",
    "<table style=\"width:100%\" border=1>",
    ligne_date(),
    f_row("Produit intérieur brut","syn.fr.gfou.fr.pib",VT,VA,b_int,b_int_old,dig=dig,bold=T,n_prev=2),
    f_row("Consommation privée","syn.fr.gfou.fr.conso",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
    f_row("Investissement","syn.fr.gfou.fr.fbcf",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
    f_row("Consommation publique","syn.fr.gfou.fr.conso_s13s15",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
    f_row("Exportations","syn.fr.gfou.fr.export",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
    f_row("Importations","syn.fr.gfou.fr.import",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
    "<tr><td><b>Contributions</b></td></tr>",
    f_row("Demande intérieure hors stocks","syn.fr.di.contrib",NIV,NIV_AN,b_int,b_int_old,"syn.fr.di.contrib.an",b_int,b_int_old,dig=dig,n_prev=3),
    f_row("Variation de stocks","syn.fr.stocks.contrib",NIV,NIV_AN,b_int,b_int_old,"syn.fr.stocks.contrib.an",b_int,b_int_old,dig=dig,n_prev=3),
    f_row("Commerce extérieur","syn.fr.comext.contrib",NIV,NIV_AN,b_int,b_int_old,"syn.fr.comext.contrib.an",b_int,b_int_old,dig=dig,n_prev=3),
    "<tr><td> * Poids du pays dans le PIB de la zone euro en 2018.</td></tr>",
    "</table>",
    
    "<h1>Allemagne (29%*) </h1>",
    "<table style=\"width:100%\" border=1>",
    ligne_date(),
    f_row("Produit intérieur brut","syn.al.pib",VT,VA,b_int,b_int_old,dig=dig,bold=T,n_prev=2),
    f_row("Consommation privée","syn.al.conso",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
    f_row("Investissement","syn.al.fbcf",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
    f_row("Consommation publique","syn.al.consopub",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
    f_row("Exportations","syn.al.export",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
    f_row("Importations","syn.al.import",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
    "<tr><td><b>Contributions</b></td></tr>",
    f_row("Demande intérieure hors stocks","syn.al.di.contrib",NIV,NIV_AN,b_int,b_int_old,"syn.al.di.contrib.an",b_int,b_int_old,dig=dig,n_prev=3),
    f_row("Variation de stocks","syn.al.stocks.contrib",NIV,NIV_AN,b_int,b_int_old,"syn.al.stocks.contrib.an",b_int,b_int_old,dig=dig,n_prev=3),
    f_row("Commerce extérieur","syn.al.comext.contrib",NIV,NIV_AN,b_int,b_int_old,"syn.al.comext.contrib.an",b_int,b_int_old,dig=dig,n_prev=3),
    "</table>",
    
    "<h1>Italie (15 %*) </h1>",
    "<table style=\"width:100%\" border=1>",
    ligne_date(),
    f_row("Produit intérieur brut","syn.it.td.b1g_s1_7ch",VT,VA,b_int,b_int_old,dig=dig,bold=T,n_prev=2),
    f_row("Consommation privée","syn.it.td.p3_s145_7ch",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
    f_row("Investissement","syn.it.td.p51g_7ch",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
    f_row("Consommation publique","syn.it.td.p3_s13_7ch",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
    f_row("Exportations","syn.it.td.p6_7ch",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
    f_row("Importations","syn.it.td.p7_7ch",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
    "<tr><td><b>Contributions</b></td></tr>",
    f_row("Demande intérieure hors stocks","syn.it.di.contrib",NIV,NIV_AN,b_int,b_int_old,"syn.it.di.contrib.an",b_int,b_int_old,dig=dig,n_prev=3),
    f_row("Variation de stocks","syn.it.stocks.contrib",NIV,NIV_AN,b_int,b_int_old,"syn.it.stocks.contrib.an",b_int,b_int_old,dig=dig,n_prev=3),
    f_row("Commerce extérieur","syn.it.comext.contrib",NIV,NIV_AN,b_int,b_int_old,"syn.it.comext.contrib.an",b_int,b_int_old,dig=dig,n_prev=3),
    "</table>",
    
    "<h1>Espagne (10%*)</h1>",
    "<table style=\"width:100%\" border=1>",
    ligne_date(),
    f_row("Produit intérieur brut","syn.es.td.b1g_7ch_ind",VT,VA,b_int,b_int_old,dig=dig,bold=T,n_prev=2),
    f_row("Consommation privée","syn.es.td.p3_s145_7ch_ind",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
    f_row("Investissement","syn.es.td.p51g_7ch_ind",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
    f_row("Consommation publique","syn.es.td.p3_s13_7ch_ind",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
    f_row("Exportations","syn.es.td.p6_7ch_ind",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
    f_row("Importations","syn.es.td.p7_7ch_ind",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
    "<tr><td><b>Contributions</b></td></tr>",
    f_row("Demande intérieure hors stocks","syn.es.di.contrib",NIV,NIV_AN,b_int,b_int_old,"syn.es.di.contrib.an",b_int,b_int_old,dig=dig,n_prev=3),
    f_row("Variation de stocks","syn.es.stocks.contrib",NIV,NIV_AN,b_int,b_int_old,"syn.es.stocks.contrib.an",b_int,b_int_old,dig=dig,n_prev=3),
    f_row("Commerce extérieur","syn.es.comext.contrib",NIV,NIV_AN,b_int,b_int_old,"syn.es.comext.contrib.an",b_int,b_int_old,dig=dig,n_prev=3),
    "</table>",
    
    "<h1>États-Unis </h1>",
    "<table style=\"width:100%\" border=1>",
    ligne_date(),
    f_row("Produit interieur brut","syn.us.pib",VT,VA,b_int,b_int_old,dig=dig,bold=T,n_prev=2),
    f_row("Consommation privee","syn.us.conso",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
    f_row("Investissement prive","syn.us.inv_hs",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
    f_row("Depenses gouvernementales","syn.us.dp",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
    f_row("Exportations","syn.us.exports",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
    f_row("Importations","syn.us.imports",VT,VA,b_int,b_int_old,dig=dig,n_prev=2),
    "<tr><td><b>Contributions</b></td></tr>",
    f_row("Demande interieure hors stocks","syn.us.di_contrib",NIV,NIV_AN,b_int,b_int_old,"syn.us.di.contrib.an",dig=dig,n_prev=2),
    f_row("Variation de stocks","syn.us.stocks.contrib",NIV,NIV_AN,b_int,b_int_old,"syn.us.stocks.contrib.an",dig=dig,n_prev=2),
    f_row("Commerce exterieur","syn.us.comext.contrib",NIV,NIV_AN,b_int,b_int_old,"syn.us.comext.contrib.an",dig=dig,n_prev=2),    "</table>",
    "</table>",
    
    "<h1> Royaume-Uni </h1>",
    "<table style=\"width:100%\" border=1>",
    ligne_date(),
    f_row("Produit interieur brut","syn.uk.pib_vol_q",VT,VA,b_int,b_int_old,dig=dig,bold=T),
    f_row("Consommation privee","syn.uk.conso_men_vol_q",VT,VA,b_int,b_int_old,dig=dig),
    f_row("Investissement","syn.uk.imt_vol_q",VT,VA,b_int,b_int_old,dig=dig),
    f_row("Consommation publique","syn.uk.conso_pub_vol_q",VT,VA,b_int,b_int_old,dig=dig),
    f_row("Exportations","syn.uk.x_vol_q",VT,VA,b_int,b_int_old,dig=dig),
    f_row("Importations","syn.uk.m_vol_q",VT,VA,b_int,b_int_old,dig=dig),
    "<tr><td><b>Contributions</b></td></tr>",
    f_row("Demande interieure hors stocks","syn.uk.di.contrib",NIV,NIV_AN,b_int,b_int_old,"syn.uk.di.contrib.an",dig=dig,n_prev=3),
    f_row("Variation de stocks","syn.uk.stocks.contrib",NIV,NIV_AN,b_int,b_int_old,"syn.uk.stocks.contrib.an",dig=dig,n_prev=3),
    f_row("Commerce exterieur","syn.uk.comext.contrib",NIV,NIV_AN,b_int,b_int_old,"syn.uk.comext.contrib.an",dig=dig,n_prev=3),
    "</table>",
    
    "<h1>Japon </h1>",
    "<table style=\"width:100%\" border=1>",
    ligne_date(),
    f_row("Produit interieur brut","syn.jp.pib",VT,VA,b_int,b_int_old,dig=dig,bold=T,n_prev=4),
    f_row("Consommation privee","syn.jp.conso",VT,VA,b_int,b_int_old,dig=dig,n_prev=4),
    f_row("Investissement","syn.jp.inv",VT,VA,b_int,b_int_old,dig=dig,n_prev=4),
    f_row("Consommation publique","syn.jp.conso_pu",VT,VA,b_int,b_int_old,dig=dig,n_prev=4),
    f_row("Exportations","syn.jp.exp_trim",VT,VA,b_int,b_int_old,dig=dig,n_prev=4),
    f_row("Importations","syn.jp.imp",VT,VA,b_int,b_int_old,dig=dig,n_prev=4),
    "<tr><td><b>Contributions</b></td></tr>",
    f_row("Demande interieure hors stocks","syn.jp.di.contrib",NIV,NIV_AN,b_int,b_int_old,"syn.jp.di.contrib.an",dig=dig,n_prev=4),
    f_row("Variation de stocks","syn.jp.stocks.contrib",NIV,NIV_AN,b_int,b_int_old,"syn.jp.stocks.contrib.an",dig=dig,n_prev=4),
    f_row("Commerce exterieur","syn.jp.comext.contrib",NIV,NIV_AN,b_int,b_int_old,"syn.jp.comext.contrib.an",dig=dig,n_prev=4),    
    
    
    "</table>",
    
    "<h1> ** FIN ** </h1>",
    "<table style=\"width:100%\" border=1>",
    "</table>",
    
    sep="")
    
    )}



