tabl_uk<-function(dig=1){
  charge<<-charge_int
return(paste(
  "<h1>Royaume-Uni</h1>",
  "<table style=\"width:100%\" border=1>",
  ligne_date(),
  f_row("Produit interieur brut","uk.pib_vol_q",VT,VA,b_int,b_int_old,dig=dig,bold=T),
  f_row("Consommation privee","uk.conso_men_vol_q",VT,VA,b_int,b_int_old,dig=dig),
  f_row("Investissement","uk.imt_vol_q",VT,VA,b_int,b_int_old,dig=dig),
  f_row("Consommation publique","uk.conso_pub_vol_q",VT,VA,b_int,b_int_old,dig=dig),
  f_row("Exportations","uk.x_vol_q",VT,VA,b_int,b_int_old,dig=dig),
  f_row("Importations","uk.m_vol_q",VT,VA,b_int,b_int_old,dig=dig),
  "<tr><td><b>Contributions</b></td></tr>",
f_row("Demande interieure hors stocks","uk.di.contrib",NIV,NIV_AN,b_int,b_int_old,"uk.di.contrib.an",dig=dig,n_prev=3),
f_row("Variation de stocks","uk.stocks.contrib",NIV,NIV_AN,b_int,b_int_old,"uk.stocks.contrib.an",dig=dig,n_prev=3),
f_row("Commerce exterieur","uk.comext.contrib",NIV,NIV_AN,b_int,b_int_old,"uk.comext.contrib.an",dig=dig,n_prev=3),
"<tr><td><b>Detail investissement</b></td></tr>",
  f_row("Investissement des entreprises","uk.imt_ent_vol_q",VT,VA,b_int,b_int_old,dig=dig),
  f_row("Investissement des menages","uk.imt_log_vol_q",VT,VA,b_int,b_int_old,dig=dig),
  f_row("Investissement public","uk.imt_pub_vol_q",VT,VA,b_int,b_int_old,dig=dig),
  "</table>",
  "<h1>Compte des menages</h1>",
  "<table style=\"width:100%\" border=1>",
  ligne_date(),
  f_row("RDB","uk.rdb_val_q",VT,VA,b_int,b_int_old,bold=T,dig=dig),
  f_row("Emploi salarie","uk.emp_sal_q",VT,VA,b_int,b_int_old,dig=dig),
  f_row("Salaires nominaux","uk.smpt",VT,VA,b_int,b_int_old,dig=dig),
  f_row("Population active","uk.pop_act_q",VT,VA,b_int,b_int_old,dig=dig),
  f_row("Emploi total","uk.emp_tot_q",VT,VA,b_int,b_int_old,dig=dig),
  f_row("Taux de chomage","uk.tx_u_bit_q",NIV,NIV_A,b_int,b_int_old,bold=T,dig=dig),
  f_row("Inflation energetique","uk.ipc_nrj",GA,GA_A,b_int,b_int_old,dig=dig),
  f_row("Inflation alimentaire","uk.ipc_alim",GA,GA_A,b_int,b_int_old,dig=dig),
  f_row("Inflation sous-jacente","uk.ipc_sj",GA,GA_A,b_int,b_int_old,dig=dig),
  f_row("Inflation totale","uk.ipc_cvs",GA,GA_A,b_int,b_int_old,bold=T,dig=dig),
  f_row("Deflateur de la consommation","uk.deflateur_conso_q",VT,VA,b_int,b_int_old,dig=dig),
  f_row("Taux d'epargne","uk.tx_s_q",NIV,NIV_A,b_int,b_int_old,bold=T,dig=dig),
  f_row("Pouvoir d'achat (avec fonds de pension)","uk.rdb_reel_fdp_q",VT,VA,b_int,b_int_old,bold=T,dig=dig),
  "</table>",sep=""))}



