tabl_al<-function(dig=1){
  charge<<-charge_int
return(paste(
  "<h1>Allemagne</h1>",
  "<table style=\"width:100%\" border=1>",
ligne_date(),
f_row("Produit interieur brut","al.pib",VT,VA,b_int,b_int_old,dig=dig,bold=T,n_prev=3),
f_row("Consommation privee","al.conso",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
f_row("Investissement","al.fbcf",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
f_row("Consommation publique","al.consopub",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
f_row("Exportations","al.export",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
f_row("Importations","al.import",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
"<tr><td><b>Contributions</b></td></tr>",
f_row("Demande interieure hors stocks","al.di.contrib",NIV,NIV_AN,b_int,b_int_old,"al.di.contrib.an",dig=dig,n_prev=3),
f_row("Variation de stocks","al.stocks.contrib",NIV,NIV_AN,b_int,b_int_old,"al.stocks.contrib.an",dig=dig,n_prev=3),
f_row("Commerce exterieur","al.comext.contrib",NIV,NIV_AN,b_int,b_int_old,"al.comext.contrib.an",dig=dig,n_prev=3),
"<tr><td><b>Detail investissement</b></td></tr>",
f_row("Investissement en construction","al.fbcfcons",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
f_row("Investissement en equipement","al.fbcfeq",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
f_row("Investissement autre","al.fbcfautre",VT,VA,b_int,b_int_old,dig=dig,n_prev=3),
"</table>",
"<h1>Compte des menages</h1>",
"<table style=\"width:100%\" border=1>",
ligne_date(),
f_row("RDB","al.rdb_insee",VT,VA,b_int,b_int_old,bold=T,dig=dig,n_prev=4),
f_row("Emploi salarie","al.emploi_sal",VT,VA,b_int,b_int_old,dig=dig,n_prev=4),
f_row("Salaires","al.smpt",VT,VA,b_int,b_int_old,dig=dig,n_prev=4),
f_row("Taux d'activite","al.taux_activite",NIV,NIV_A,b_int,b_int_old,dig=dig,n_prev=4),
f_row("Population active","al.popact",VT,VA,b_int,b_int_old,dig=dig,n_prev=4),
f_row("Emploi total","al.emploi_total",VT,VA,b_int,b_int_old,dig=dig,n_prev=4),
f_row("Taux de chomage","al.tx_u_cnt",NIV,NIV_A,b_int,b_int_old,bold=T,dig=dig,n_prev=4),
f_row("Inflation energetique","al.ipch_energie_t",GA,GA_A,b_int,b_int_old,dig=dig,n_prev=3),
f_row("Inflation alimentaire","al.ipch_alim_t",GA,GA_A,b_int,b_int_old,dig=dig,n_prev=3),
f_row("Inflation sous-jacente","al.ipch_sj_t",GA,GA_A,b_int,b_int_old,dig=dig,n_prev=3),
f_row("Inflation totale","al.ipch_t",GA,GA_A,b_int,b_int_old,bold=T,dig=dig,n_prev=3),
f_row("Deflateur de la consommation","al.def_conso",VT,VA,b_int,b_int_old,dig=dig,n_prev=4),
f_row("Pouvoir d'achat","al.pvr_achat",VT,VA,b_int,b_int_old,bold=T,dig=dig,n_prev=4),
f_row("Taux d'epargne","al.tx_s_maison_b",NIV,NIV_A,b_int,b_int_old,bold=T,dig=dig,n_prev=4),
"</table>",sep=""))}


